### ISSUE TITLE
Modelagem do banco de dados

### ISSUE THREAD

**Issue by Throyer** [E-Lab-Software/bibliotech#2]
# Fazer  a modelagem do banco de dados

**Para fazer a modelagem leve em conta estas funcionalidades**

1. **Gerenciamento de Livros**:
   - Adicionar, editar e remover livros.
   - Cadastrar informações detalhadas sobre os livros, como título, autor, gênero, ISBN, data de publicação, etc.
   - Pesquisa de livros por diferentes critérios (autor, título, gênero).

2. **Gerenciamento de Membros**:
   - Registrar novos membros.
   - Editar e remover informações dos membros.
   - Visualizar o histórico de empréstimos dos membros.

3. **Empréstimos e Devoluções**:
   - Registrar empréstimos de livros para os membros.
   - Registrar devoluções de livros.
   - Notificar membros sobre a data de devolução.

4. **Autenticação e Autorização**:
   - Sistema de login e registro para bibliotecários e membros.
   - Diferentes níveis de acesso (ex: bibliotecários podem adicionar livros, membros podem apenas visualizar).

5. **Relatórios e Análises**:
   - Gerar relatórios sobre livros mais emprestados.
   - Analisar padrões de leitura e preferências dos membros.

6. **Recomendações de Livros**:
   - Sistema de recomendação baseado nas preferências e histórico de leitura dos membros.

**Comment by Throyer** [comment]
@Domlcforce123 example
![image](https://github.com/user-attachments/assets/500c9373-405a-46cb-8bfb-e8a811dfec53)

**Comment by Throyer** [comment]
https://app.diagrams.net/

**Comment by Domlcforce123** [comment]
Bom dia caro futuro chefe renato, veja a seguir meu diagrama e me notifique caso queira mudanças no mesmo 


Att DOMLCFORCE12345678910

[Modelagem do banco de dados.pdf](https://github.com/user-attachments/files/16581448/Modelagem.do.banco.de.dados.pdf)

**Comment by Throyer** [comment]
o nome das tabelas precisa ser no padrão snake_case, e você pode me explicar a função da tabela loan history? e como ela difere da tabela loan?

na tabela member, o campo nome e sobrenome pode ser um campo só

@Domlcforce123

**Comment by Domlcforce123** [comment]
respondendo sua pergunta, eu visando a otimização futura, tentei separar as citadas, para otimização porem como não sera necessário reformulei de uma maneira mais simples, e ajustei os campos e reformulei no padrão snake_case

[Modelagem do banco de dados.pdf](https://github.com/user-attachments/files/16581852/Modelagem.do.banco.de.dados.pdf)

Favor revisar
